name: Lilac agent CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
 run:
  working-directory: agent

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lilac Agent CI
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: 'agent -> target'
    - name: Build server
      run: cargo build
    - name: Run tests for agent
      run: cargo test
